[package]
name = "svart"
version = "3.0.0"
edition = "2021"

[dependencies]
cozy-chess = "0.3.2"
once_cell = "1.17.1"
chrono = "0.4.24"
fastrand = "1.9.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

