[package]
name = "svart"
version = "2.2.0"
edition = "2021"

[dependencies]
# Use Cozy-Chess for move-gen and board representation
cozy-chess = "0.3.1"
once_cell = "1.17.1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

