[package]
name = "svart"
version = "3.5.0"
edition = "2021"

[dependencies]
cozy-chess = "0.3.2"
once_cell = "1.17.1"
chrono = "0.4.24"
fastrand = "1.9.0"
ctrlc = "3.2.5"
tabled = "0.11.1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
